// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZjqECLpHOk682qd4YjTU2SwLN8kO-qM',
    appId: '1:504771400915:web:9147a517adb1fcf3bdf026',
    messagingSenderId: '504771400915',
    projectId: 'bai-system',
    authDomain: 'bai-system.firebaseapp.com',
    storageBucket: 'bai-system.appspot.com',
    measurementId: 'G-061LCFEXSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm0HLw9mz9btzjsdekvCh_oy3ErNuwekw',
    appId: '1:504771400915:android:4556043ab0ef8397bdf026',
    messagingSenderId: '504771400915',
    projectId: 'bai-system',
    storageBucket: 'bai-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQX_fYASwqnSadVmJdElNlRekFIN5a4sE',
    appId: '1:504771400915:ios:2b989bd8523e8cb2bdf026',
    messagingSenderId: '504771400915',
    projectId: 'bai-system',
    storageBucket: 'bai-system.appspot.com',
    iosBundleId: 'com.example.fptuBikeParkingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQX_fYASwqnSadVmJdElNlRekFIN5a4sE',
    appId: '1:504771400915:ios:2b989bd8523e8cb2bdf026',
    messagingSenderId: '504771400915',
    projectId: 'bai-system',
    storageBucket: 'bai-system.appspot.com',
    iosBundleId: 'com.example.fptuBikeParkingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZjqECLpHOk682qd4YjTU2SwLN8kO-qM',
    appId: '1:504771400915:web:4459ffab77a9586cbdf026',
    messagingSenderId: '504771400915',
    projectId: 'bai-system',
    authDomain: 'bai-system.firebaseapp.com',
    storageBucket: 'bai-system.appspot.com',
    measurementId: 'G-0P51DJE9B6',
  );
}